### ISSUE TITLE
./cli.js在Ubuntu 14.04.1 LTS中会报错：/usr/bin/env: node --harmony --harmony_arrow_functions: No such file or directory

### ISSUE THREAD

**Issue by liu7yong** [ChiChou/etacsufbo#2]
google的结论是，linux中env不支持带参数的方式执行：
http://stackoverflow.com/questions/24548733/how-to-make-a-nodejs-file-executable-with-harmony-option
http://stackoverflow.com/questions/3306518/cannot-pass-an-argument-to-python-with-usr-bin-env-python

按照上面的建议改成如下方式:
```bash
#!/usr/bin/node --harmony
```
则会报错
```
/home/liuyong/nodejs/etacsufbo/cli.js:38
          console.log(`Error: ${ex.description} at line ${ex.lineNumber}, col 
                      ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by ChiChou** [comment]
不是这个问题，是你的 node.js 版本太低了。请使用 4.0 以上的版本。

在 848be8db3f2ca211ba902a4d592d47f1635cc1ee 中强制加入了 engine 限制。

**Comment by ChiChou** [comment]
由于这是一个实验项目，会优先使用最新的 node.js 特性，不会向下兼容，随时可能出现 API 的 breaking change
