### ISSUE TITLE
Don't use JSON.parse(JSON.stringify(originAst)) to clone a AST tree

### ISSUE THREAD

**Issue by 8qwe24657913** [ChiChou/etacsufbo#4]
test case: /foo/
returns: [object Object]

原因： RT，在js中有regexp字面量时，解析出AST的对应节点的value属性是一个regexp，JSON.stringify会把这个regexp变成一个空object，输出时隐式调用toString()，所以结果是[object Object]，相当于JSON.parse(JSON.stringify(/foo/)).toString();

位置：https://github.com/ChiChou/etacsufbo/blob/master/lib/simplifier.js#L37

**Comment by ChiChou** [comment]
暂时移除，区别只是会在原始的 ast 上做原地修改。感觉对于暴露的 API 来说也并不需要考虑中间数据的 immutable
